# coding: utf-8
from django.core.management.base import BaseCommand

from django.core.mail import EmailMessage

from django.template import Context, Template
from django.template.loader import render_to_string
import json

from django.conf import settings

MAIL_TITLE = "ODTÜ Bilgisayar Topluluğu 22. Programlama Yarışması"
MAIL_TEMPLATE = """
ODTÜ Bilgisayar Topluluğu 22. Programlama Yarışması başlıyor!

Yarışmamıza kaydınızı yaptırdığınızı unutmamışsınızdır ama biz yine de hatırlatalım ve biraz da sizi bilgilendirelim istedik.

Yarışmamız 22 Mart Cuma akşamı saat 21:00’de başlayacak ve 25 Mart Pazartesi saat 09:00’a kadar sürecek. Toplam 60 saat süreniz olacak ve süreniz sistem açıldığında başlayacak. Sisteme istediğiniz zaman giriş yapabilecek, istediğinizde sistemden çıkış yapıp çözmeye daha sonra devam edebileceksiniz. Yarışmanın ilk 52 saatinde takımların sıralamaları herkese açık olacak, sıralama ekranı son 8 saatte kapatılacak.

Final etabına katılmaya hak kazanan 17 takım için yarışmayı takip eden hafta içinde asiller ve yedekler olmak üzere 2 liste yayınlanacak ve asil listeden önlisans ya da lisans öğrencisi olduklarına dair öğrenci belgeleri istenecek. Asil listede olup öğrenci belgesi yollamayan takımlar yerine yedek listedeki takımlarla iletişime geçilecek ve finale kalan 17 takım böylece belirlenmiş olacak.

Yarışma sistemine mailin sonunda bulabileceğiniz giriş bilgileriyle saat 21:00’den itibaren yarisma.cclub.metu.edu.tr üzerinden giriş yapabileceksiniz. Herhangi bir sorunuz olursa cclub@metu.edu.tr adresine mail atarak bize ulaşabilirsiniz.

ODTÜ Bilgisayar Topluluğu olarak başarılar dileriz!

Takım adı: {{ team_name }}
Üyeler:
{{ name1 }}
{{ name2 }}
{{ name3 }}

Giriş bilgileri:
Giriş maili (takım kaptanının mail adresi): {{ mail1 }}
Şifre: {{ passwd }}
"""

class Command(BaseCommand):
	help = """
	reads email addresses, team names and passwords from a file
	and guns the stuff to the emails it found.
	"""

	def handle(self, *args, **options):
		teams = json.load(open('/app/data/out.json'))
		sent_mails = [
			'n.musevitoglu@ug.bilkent.edu.tr',
'akin.parkan@ug.bilkent.edu.tr',
'b.ozcomlekci@ug.bilkent.edu.tr',
'batuhan.tosyali@ug.bilkent.edu.tr',
'alptekin.onder@ug.bilkent.edu.tr',
'm.berkose@ug.bilkent.edu.tr',
'yusufcemalcelebi@gmail.com',
'abd.beik@me.com',
'hasarfeyzullah@gmail.com',
'elifnurakalin@gmail.com',
'emreaygun86@gmail.com',
'egekaya1999@gmail.com',
'can.sabri.09@gmail.com',
'n.musevitoglu@ug.bilkent.edu.tr',
'ekindursun@gmail.com',
'yusuf.nevzat.sengun@gmail.com',
'zdaytac@gmail.com',
'yusufcemalcelebi@gmail.com',
'emreaygun86@gmail.com',
'can.sabri.09@gmail.com',
'trtyos@gmail.com',
'uygar.yasar@metu.edu.tr',
'egekaya1999@gmail.com',
'zdaytac@gmail.com',
'elifnurakalin@gmail.com',
'seyma2015112@gmail.com',
'nkyahse1999@gmail.com',
'suleymanince2000@gmail.com',
'muratakburakma@gmail.com',
'hasarfeyzullah@gmail.com',
'nergiserva@hotmail.com',
'sulenurpolat@outlook.com',
'ekindursun@gmail.com',
'tugrahan.gorkem@hotmail.com',
'tugba.tumer@metu.edu.tr',
'emre.gullu@metu.edu.tr',
'muratakburakma@gmail.com',
'n.musevitoglu@ug.bilkent.edu.tr',
'yusuf.nevzat.sengun@gmail.com',
'ammar.albakri.99@gmail.com',
'oguzhanozcelik0151@gmail.com',
'ysssoylu@gmail.com',
'abd.beik@me.com',
'suleymanince2000@gmail.com',
'nkyahse1999@gmail.com',
'oguzhanozcelik0151@gmail.com',
'nergiserva@hotmail.com',
'seyma2015112@gmail.com',
'sulenurpolat@outlook.com',
'ahmetemin.unal@agu.edu.tr',
'matays99@gmail.com',
'trtyos@gmail.com',
'ammar.albakri.99@gmail.com',
'alpkeles99@gmail.com',
'eren.erisken@metu.edu.tr',
'ysssoylu@gmail.com',
'uygar.yasar@metu.edu.tr',
'tugba.tumer@metu.edu.tr',
'tugrahan.gorkem@hotmail.com',
'fthi.cetin@gmail.com',
'dbildibay@gmail.com',
'tokmaksaid@gmail.com',
'matays99@gmail.com',
'mehmet94nto@gmail.com',
'eren.erisken@metu.edu.tr',
'emre.gullu@metu.edu.tr',
'alpkeles99@gmail.com',
'e.erolayhan@gmail.com',
'mehmet94nto@gmail.com',
'mertcancakmak1998@gmail.com',
'dbildibay@gmail.com',
'e.erolayhan@gmail.com',
'fthi.cetin@gmail.com',
'tokmaksaid@gmail.com',
'myavuzkara@gmail.com',
'ahmetemin.unal@agu.edu.tr',
'mhkarazeybek98@gmail.com',
'myavuzkara@gmail.com',
'alperen.0311@gmail.com',
'devlops17a18@gmail.com',
'mertcancakmak1998@gmail.com',
'ozan.incesulu@gmail.com',
'fahedshaabani@std.sehir.edu.tr',
'alperen.0311@gmail.com',
'berk.arslan@ceng.metu.edu.tr',
'magedmahmoud@std.sehir.edu.tr',
'devlops17a18@gmail.com',
'mhkarazeybek98@gmail.com',
'kutayacar@std.sehir.edu.tr',
'abdullah-taha13@hotmail.com',
'kutayacar@std.sehir.edu.tr',
'magedmahmoud@std.sehir.edu.tr',
'fahedshaabani@std.sehir.edu.tr',
'mrtkcu0101@gmail.com',
'e223797@metu.edu.tr',
'ozan.incesulu@gmail.com',
'abdullah-taha13@hotmail.com',
'ibracay4545@gmail.com',
'mrtkcu0101@gmail.com',
'e217118@metu.edu.tr',
'ibracay4545@gmail.com',
'e223797@metu.edu.tr',
'egeunalan@gmail.com',
'kurt9804@gmail.com',
'egeunalan@gmail.com',
'atakan_kuru@outlook.com.tr',
'e223693@metu.edu.tr',
'kurt9804@gmail.com',
'melih_murat_pesmen@hotmail.com',
'berk.arslan@ceng.metu.edu.tr',
'anasothman29@gmail.com',
'melih_murat_pesmen@hotmail.com',
'atakan_kuru@outlook.com.tr',
'uguruy3939@gmail.com',
'olut.sahin@gmail.com',
'e223693@metu.edu.tr',
'e217118@metu.edu.tr',
'akin.parkan@ug.bilkent.edu.tr',
'thedarkm0@gmail.com',
'huseyinnakuzum@gmail.com',
'anasothman29@gmail.com',
'kizilkayaarda@gmail.com',
'sereforensoy@gmail.com',
'b.ozcomlekci@ug.bilkent.edu.tr',
'thedarkm0@gmail.com',
'soyhanerinan@hotmail.com',
'kasapoglu.ek@gmail.com',
'huseyinnakuzum@gmail.com',
'olut.sahin@gmail.com',
'uguruy3939@gmail.com',
'erensenogl@gmail.com',
'gokberkeser@gmail.com',
'kizilkayaarda@gmail.com',
'kasapoglu.ek@gmail.com',
'akin.parkan@ug.bilkent.edu.tr',
'sahinonur2000@hotmail.com',
'sereforensoy@gmail.com',
'soyhanerinan@hotmail.com',
'sh.khasmamad@gmail.com',
'alizada.physics@gmail.com',
'sahinonur2000@hotmail.com',
'erensenogl@gmail.com',
'b.ozcomlekci@ug.bilkent.edu.tr',
'dogukan10cav@gmail.com',
'gokberkeser@gmail.com',
'esuzgen15@ku.edu.tr',
'msamikaraca@protonmail.com',
'eatisay15@ku.edu.tr',
'alizada.physics@gmail.com',
'sh.khasmamad@gmail.com',
'ahmetterzi24@gmail.com',
'dogukan10cav@gmail.com',
'ahmetterzi24@gmail.com',
'bsipahioglu15@ku.edu.tr',
'e231019@metu.edu.tr',
'oozdemir15@ku.edu.tr',
's.ugursahin@gmail.com',
'eatisay15@ku.edu.tr',
'esuzgen15@ku.edu.tr',
'nilgokcimen@gmail.com',
'iiilker99@gmail.com',
'san.gokhan@metu.edu.tr',
'ozacetyusuf@gmail.com',
'yasindemek75@gmail.com',
'nilgokcimen@gmail.com',
'atakangs_98@hotmail.com',
'mehmetutkuduzen@gmail.com',
'bsipahioglu15@ku.edu.tr',
'oozdemir15@ku.edu.tr',
'abdulmalek.s.a.shefat@gmail.com',
'msamikaraca@protonmail.com',
'yasindemek75@gmail.com',
'ozacetyusuf@gmail.com',
'fatihyalic@gmail.com',
'idilsulo@gmail.com',
'e231019@metu.edu.tr',
'mehmetutkuduzen@gmail.com',
'iiilker99@gmail.com',
'ismailsahal89@gmail.com',
'ismntr@hotmail.com',
'bktgnc06@gmail.com',
's.ugursahin@gmail.com',
'idilsulo@gmail.com',
'herkan591@hotmail.com',
'yunus.uzun@metu.edu.tr',
'yesilyurt.selim@metu.edu.tr',
'abdulmalek.s.a.shefat@gmail.com',
'tolunayereni@gmail.com',
'ismntr@hotmail.com',
'bktgnc06@gmail.com',
'fatihyalic@gmail.com',
'tolunayereni@gmail.com',
'atakangs_98@hotmail.com',
'herkan591@hotmail.com',
'yunus.uzun@metu.edu.tr',
'yesilyurt.selim@metu.edu.tr',
'san.gokhan@metu.edu.tr',
'batuhan.tosyali@ug.bilkent.edu.tr',
'harunarmut0@gmail.com',
'cengizhanbasakk@gmail.com',
'harunarmut0@gmail.com',
'ezgibrng@icloud.com',
'm.berkose@ug.bilkent.edu.tr',
'zelihabektas25@gmail.com',
'kuzey.emre@metu.edu.tr',
'ismailsahal89@gmail.com',
'alptekin.onder@ug.bilkent.edu.tr',
'kbra_gven1996@hotmail.com',
'melisalaratici@hotmail.com',
'cengizhanbasakk@gmail.com',
'zelihabektas25@gmail.com',
'evren.ekici@metu.edu.tr',
'ttosun350@gmail.com',
'melisalaratici@hotmail.com',
'kuzey.emre@metu.edu.tr',
'kbra_gven1996@hotmail.com',
'ttosun350@gmail.com',
'sefik.palazoglu.s@gmail.com',
'muhittinpalamutcu@gmail.com',
'batuhan.tosyali@ug.bilkent.edu.tr',
'm.berkose@ug.bilkent.edu.tr',
'alptekin.onder@ug.bilkent.edu.tr',
'sabrimete99@gmail.com',
'gorkemunal0@gmail.com',
'ibrahimdede3@gmail.com',
'mmsahin.35@gmail.com',
'sabrimete99@gmail.com',
'sefik.palazoglu.s@gmail.com',
'ibrhmglcyz@hotmail.com',
'mmsahin.35@gmail.com',
'yilmaz_nezih@hotmail.com',
'oguzhannoztaskin@gmail.com',
'gorkemunal0@gmail.com',
'ibrhmglcyz@hotmail.com',
'evren.ekici@metu.edu.tr',
'yusufozben@gmail.com',
'ecembalikci@hotmail.com',
'erdemkopan.ek@gmail.com',
'oguzhannoztaskin@gmail.com',
'muhittinpalamutcu@gmail.com',
'ecembalikci@hotmail.com',
'ezgibrng@icloud.com',
'omyanik8@gmail.com',
'yilmaz_nezih@hotmail.com',
'alicaferozer@gmail.com',
'metin__ur.1997@hotmail.com',
'ab.atakishiyev@gmail.com',
'ibrahimdede3@gmail.com',
'erdemkopan.ek@gmail.com',
'omyanik8@gmail.com',
'monosec15@gmail.com',
'resulsaparov@gmail.com',
'furkan.turkal@gmail.com',
'ab.atakishiyev@gmail.com',
'monosec15@gmail.com',
'resulsaparov@gmail.com',
'tekinenesmalik@hotmail.com',
'alparslanylmaz@gmail.com',
'yusufozben@gmail.com',
'tahsincankose@gmail.com',
'alicaferozer@gmail.com',
'yzozgul98@gmail.com',
'tahsincankose@gmail.com',
'yzozgul98@gmail.com',
'tekinenesmalik1@gmail.com',
'alparslanylmaz@gmail.com',
'metin__ur.1997@hotmail.com',
'furkan.turkal@gmail.com',
'tekinenesmalik1@gmail.com',
'tekinenesmalik@hotmail.com'
		]

		for team in teams:
			msg = Template(MAIL_TEMPLATE).render(Context(team))

			mails = [team["mail1"], team["mail2"], team["mail3"]]

			for i in range(len(mails) - 1, -1, -1):
				if mails[i] == '' or mails[i] in sent_mails:
					del mails[i]

			email = EmailMessage(MAIL_TITLE,
								msg,
								to=mails)
			email.send()
