# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-08 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_auto_20190902_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='team_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='team_slug',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
