# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-22 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0068_hide_scoreboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='team_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Tak\xc4\xb1m ad\xc4\xb1'),
        ),
    ]
