# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-22 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0069_profile_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='team_slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name=b'Tak\xc4\xb1m slugu'),
        ),
    ]
