# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-01 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0087_auto_20190831_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='judge.ProblemGroup', verbose_name='problem group'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='types',
            field=models.ManyToManyField(blank=True, to='judge.ProblemType', verbose_name='problem types'),
        ),
    ]
